### ISSUE TITLE
How-To: Rubric Task List

### ISSUE THREAD

**Issue by jgagne** [jtexX/how-to#1]
# How-To
## Rubric Task List

20 tasks (`5 points` each) with 3 extra credit tasks.

### Meta

`5 points`

- [ ] Use of accessible, responsible, and mobile-friendly metadata:
  - Use of `lang="en-us"` to define the language of the document content.
  - Use of `<meta charset="utf-8">` as the first meta tag in `<head>` element to define proper character encoding.
    - See [Character encodings for beginners](https://www.w3.org/International/questions/qa-what-is-encoding)
  - Use of `<meta name="viewport" content="width=device-width, initial-scale=1">` for mobile-friendly layout.
  - Use of the `<link>` element for an external style sheet for *all* styles; avoid use of an embedded style sheet (`<style>`…`</style>`) and any inline style (`style="…"`).
    - `<link rel="stylesheet" href="css/main.css">`
  - Use of the `<link>` element for canonical content (for search engines to index the original source of content to avoid duplicate content).
    - `<link rel="canonical" href="https://www.bonappetit.com/recipe/basic-crepes">` .
  - Use of the `<title>` element to describe the document content in a concise and meaningful way.
    - See [`<title>`: The Document Title element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title)
  - Use of `<meta name="author" content="Name Surname">` to define the author of the webpage or site.

For example:
```
<!doctype html>
<html lang="en-us">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="css/main.css">
  <title>Short, Descriptive Title</title>
  <link rel="canonical" href="original-sources-of-content.com">
  <meta name="author" content="Name Surname">
</head>
<body>

<!-- Content -->

</body>
</html>
```

### Markup & Style

`45 points`

- [ ] Use of lowercase alphabet for all markup, style, and file/folder names (also `class`, `id`, and file/folder names should not include spaces, instead use a hyphen (`-`) in place of any space).
  - For example: Use `<section id="sauce-preparation">` in place of `<section id="Sauce Preparation">`, `main.css` in place of `Main.CSS`, etc.
- [ ] Avoid use of [obsolete elements](https://css-tricks.com/why-do-some-html-elements-become-deprecated/#which-html-elements-are-now-deprecated), misuse of previously (pre-HTML5) presentational elements, or use of elements that are counter to responsive web design.
  - Such as use of the `<center>` element for centering content, use CSS instead (`text-align` or `margin` properties).
    - See [Centering in CSS](https://ishadeed.com/article/learn-css-centering/)
  - Such as use of the `<hr>` element for a horizontal rule, use CSS instead (`border` property).
    - See [The small & hr elements](http://html5doctor.com/small-hr-element/)
  - Such as use of the `<br>` for a line break, use the `<p>` element instead to group text into paragraphs and avoid a manual line break with the `<br>` element altogether to improve responsive text-based content.
    - See [`<br>`: The Line Break element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br)
- [ ] Use of semantic section (`header`, `nav`, `section`, etc.) and semantic text-level elements (`strong`, `em`, `time`, etc.).
  - See HTML5 Doctor’s [HTML5 Element Index](http://html5doctor.com/#glossary)
- [ ] Use of description `<dl>`, ordered `<ol>`, and unordered `<ul>` lists for defining a set of terms, instructions, navigational links, etc.
  - See [Semantic Structure: Regions, Headings, and Lists](https://webaim.org/techniques/semanticstructure/#lists)
  - See also [Creating Lists](https://learn.shayhowe.com/html-css/creating-lists/)
- [ ] Use of proper [typographical characters](http://htmlarrows.com) for fractions, punctuation, symbols, etc. (Use human-readable characters only, not the code/entity; for example: Use `½`, instead of `1/2` [faux fraction] or `&frac12;` [code/entity]).
- [ ] Use of [accessible colors](https://accessible-colors.com) contrast ratios with a [cohesive color palette](https://www.smashingmagazine.com/2016/04/web-developer-guide-color/) throughout the page for typography, borders, background colors, links, and imagery.
- [ ] Use of basic [typographic](https://learn.shayhowe.com/html-css/working-with-typography/) and [box model layout](https://learn.shayhowe.com/html-css/opening-the-box-model/) (focusing on `padding`, `border`, and `margin`) styles.
- [ ] Use of [web safe fonts](https://www.fonts.com/content/learning/fyti/using-type-tools/fonts-on-the-web)
  - See [CSS font stacks](http://www.cssfontstack.com) for fallback replacements.
- [ ] Use CSS to style all links beyond the default blue/purple colors. (Also consider the style of link interactive states `:hover` and `:focus`.)
  - See [How to Style Links in CSS](https://www.freecodecamp.org/news/how-to-style-links-in-css/)

### Layout

`5 points`

- [ ] Use of a mobile first, single-column layout for small screens with a max-width and centered layout for wider screens.

For example:
```
body {
  max-width: 48rem; /* Max-width layout for wider screens */
  padding: 0 1rem;
  margin: 0 auto;
}
```

### Images

`20 points`

See [Decoding & Loading Images](https://github.com/ec-student/img-async-lazy) demo.

- [ ] Avoid use of the `iframe` element for animated GIFs; use the `img` element instead for embedded images (static and animated).
- [ ] Use of the `<img>` element for embedding images with the following attributes:
  - Required: `alt` defines meaningful alternative text (alt text).
    - See [When writing alt text, ask yourself this question](https://www.centercentre.com/2016/06/09/2016-06-09-when-writing-alt-text-ask-yourself-this-question/)
  - Required: `src` defines the source of the embedded content.
  - Required: `width` and `height` defines the intrinsic width and height of an image.
    - See [Setting Height and Width on Images is Important Again](https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/)
  - Optional: `decoding` defines whether to decode the image in parallel or along with the rest of the page content.
    - See [Synchronous / Asynchronous Image Decode using〈img decoding〉Attribute](https://usefulangle.com/post/277/img-decoding-attribute)
  - Optional: `loading` defines the priority of an image depending on where it’s located within a page.
    - See [Browser-level image lazy-loading for the web](https://web.dev/browser-level-image-lazy-loading/)
- [ ] Use of [responsive images](https://alistapart.com/article/fluid-images/) CSS markup.
  - For example:
  ```
  img {
    width: auto;
    max-width: 100%;
    height: auto;
  }
  ```
- [ ] Resize and optimize images to the size they appear in the browser at your `max-width` layout (and at a maximum, double the width for retina and super retina displays).
  - In Photoshop: save bitmap (raster) images using Photoshop, export `Save for Web (Legacy)…` photographs as a JPG (`.jpg`) using the preset `JPEG High` or `JPEG Medium` (depending on quality and file size) and illustrations as a PNG (`.png`) using the preset `PNG-8 128 Dithered` (less colors [max 256]) or `PNG-24` (more colors [millions]).
  - In [Squoosh](https://squoosh.app): Use `MozJPEG` to optimize JPGs and use `OptiPNG` to optimize PNGs. (You may resize an image in Squoosh as well.)
  - In [ImageOptim](https://imageoptim.com/mac): Enable all image optimizations options via `ImageOptim` > `Preferences…` > `Enable` (left sidebar in General settings).
  - **Note:** Aim for an optimized file size around `150 KB` and below (max `200 KB`).

### Validation

`15 points`

- [ ] [Validate HTML](https://validator.w3.org/nu/) (No errors; warnings are ok, but try to resolve)
- [ ] [Validate CSS](http://jigsaw.w3.org/css-validator/) (No errors; warnings are ok, but try to resolve)
- [ ] [Color Contrast Accessibility Validator](https://color.a11y.com/) (All color combinations should pass: *Congratulations! No automated color contrast issues found on the webpage tested.*)

### Git Organized

`10 points`

Remember to use lowercase naming…

- [ ] Repo should contain only essential files:
  - `index.html`
  - `css` (folder containing an external stylesheet)
    - For example: `main.css`
  - `img` (folder containing images)
    - For example: `yummy-cakes.jpg`
  - `README.md`
    - Update with a proper heading (title) and paragraph (description) using [Markdown](https://www.markdownguide.org/basic-syntax/).
- [ ] Add a description and URL to the About section of your GitHub repo.

### Extra Credit

`15 points`

- [ ] Use of consistent text size and spacing (`font-size`, `line-height`, and `margin`) for paragraphs and lists to create a seamless reading experience from one text grouping to the next.
  - See [Styling lists](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_lists)
- [ ] Use of CSS generated content (pseudo-elements such as `::before`, `::after`, and `::marker`) to add visual progressive enhancements.
  - See [CSS Generated Content and Visual Enhancements With Pseudo-Elements](https://jsbin.com/tetorob/edit?html,css,output)
- [ ] Use of original artwork (photography, illustration, etc.) with inclusion of credit byline.

For example:
```
<figure>
  <img alt="A plate of freshly baked chocolate chip cookies." src="img/chocolate-chip-cookies.jpg" width="1280" height="720" decoding="async">
  <figcaption class="image-credit">Photo by Name Surname</figcaption>
</figure>
```
